import Head from 'next/head'
import Image from 'next/image'
import Video from '../components/video'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import MainComponent from '../components/MainComponent'
import { useState } from 'react'

export default function Home() {
  const [show, setShow] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile Tilt Screen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <MainComponent />
        {show && <Video />}
      </main>
    </div>
  )
}
